language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

notifications:
  email: false    # default notification method
  slack:
    rooms:
      secure: dktmsgYaQ2RA9mL21Mnsh7I2a/eyaMPkv5qyPkEmAjEUhMUlPBWhu1Ou75wAyGv1UCgsNBln7US/YPA/E1WD0Cp5DKLRWhdcrUCxRNqQEH6osL7AVRX4z4eh99JHzkdJSk/NeiffMtLGOw7hufR92ZqjZbdzpJZTulsCvw+xKMqV5V7qfjdH7dd3DIPPpLlMlBEWNwdMSy073EsdOPqSO4BcT9FYy6whTXUWnO/SwsnEh1o9UfST9F6Srks6LuUS9QGY0uhfrXA82Amvxftg7+RcPH33DOTdpv4K/OKQZoHHxZRM/gaWznSl0Vsv2EeJivYEFixPeTtyTN3bqL/SDPrYjzjAn3VNhu7/t/1keFx2czu+rbDKvSGFVJXhzA+IiNg1WW1Z5ix2PGELAyIKwy7p7xcq7mmmevj2T+4z6DbX6gwERB4feXwxx6WlikPJs2vasC1u9bdzEUdoIAYw9t/qf+3vsX2gm76p/7X2JYFMEScuD9NJxplTle8Dj8KbaacS9IIS/J62BbRXsczPVp0EivffXp1I/LJQWmcGNEXFimi1TbxvtC1thsJyKoLXBxSMGn5+QLoJiaC29uusrLdSmJUOeXbA41OWU7r2mNrziRqOMk54M447mcFPLjQ5U40D3dYucoImvm4tJeiHEdCd1XjCpJiWuIKyu2HAjaA=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
      - "Commit: %{commit_subject}"
      - "```%{commit_message}```"

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"